// AUTOGENERATED by onchain/contract-data/sprites/tools/gen-sleeping-atlas.mjs.
// DO NOT EDIT BY HAND. Edit onchain/contract-data/sprites/buddies-source.mjs and regenerate.
//
// Frame-0 body slice + hat rows for the local sleeping render. Mirrors what
// BuddySpriteData.getBodyRow(species, 0, row) and getHatRow(hat) return on-chain.

import type { Hat, Species } from "./bone-deriver";

export const BODY_FRAME_0: Record<Species, readonly string[]> = {
  duck: [
    "                 ",
    "       __        ",
    "     <(0 )___    ",
    "      (  ._>     ",
    "       `--´     ",
  ],
  goose: [
    "                 ",
    "        (0>      ",
    "        ||       ",
    "      _(__)_     ",
    "       ^^^^      ",
  ],
  blob: [
    "                 ",
    "      .----.     ",
    "     ( 0  0 )    ",
    "     (      )    ",
    "      `----´    ",
  ],
  cat: [
    "                 ",
    "      /\\_/\\      ",
    "     ( 0   0)    ",
    "     (  ω  )    ",
    "     (\")_(\")     ",
  ],
  dragon: [
    "                 ",
    "     /^\\  /^\\    ",
    "    <  0  0  >   ",
    "    (   ~~   )   ",
    "     `-vvvv-´   ",
  ],
  octopus: [
    "                 ",
    "      .----.     ",
    "     ( 0  0 )    ",
    "     (______)    ",
    "     /\\/\\/\\/\\    ",
  ],
  owl: [
    "                 ",
    "      /\\  /\\     ",
    "     ((0)(0))    ",
    "     (  ><  )    ",
    "      `----´    ",
  ],
  penguin: [
    "                 ",
    "      .---.      ",
    "      (0>0)      ",
    "     /(   )\\     ",
    "      `---´     ",
  ],
  turtle: [
    "                 ",
    "      _,--._     ",
    "     ( 0  0 )    ",
    "    /[______]\\   ",
    "     ``    ``    ",
  ],
  snail: [
    "                 ",
    "    0    .--.    ",
    "     \\  ( @ )    ",
    "      \\_`--´    ",
    "     ~~~~~~~     ",
  ],
  ghost: [
    "                 ",
    "      .----.     ",
    "     / 0  0 \\    ",
    "     |      |    ",
    "     ~`~``~`~    ",
  ],
  axolotl: [
    "                 ",
    "   }~(______)~{  ",
    "   }~(0 .. 0)~{  ",
    "     ( .--. )    ",
    "     (_/  \\_)    ",
  ],
  capybara: [
    "                 ",
    "     n______n    ",
    "    ( 0    0 )   ",
    "    (   oo   )   ",
    "     `------´   ",
  ],
  cactus: [
    "                 ",
    "    n  ____  n   ",
    "    | |0  0| |   ",
    "    |_|    |_|   ",
    "      |    |     ",
  ],
  robot: [
    "                 ",
    "      .[||].     ",
    "     [ 0  0 ]    ",
    "     [ ==== ]    ",
    "     `------´   ",
  ],
  rabbit: [
    "                 ",
    "      (\\__/)     ",
    "     ( 0  0 )    ",
    "    =(  ..  )=   ",
    "     (\")__(\")    ",
  ],
  mushroom: [
    "                 ",
    "    .-o-OO-o-.   ",
    "   (__________)  ",
    "      |0  0|     ",
    "      |____|     ",
  ],
  chonk: [
    "                 ",
    "     /\\    /\\    ",
    "    ( 0    0 )   ",
    "    (   ..   )   ",
    "     `------´   ",
  ],
};

export const HAT_ROWS: Record<Hat, string> = {
  none: "             ",
  crown: "    \\^^^/    ",
  tophat: "    [___]    ",
  propeller: "     -+-     ",
  halo: "    (   )    ",
  wizard: "     /^\\     ",
  beanie: "    (___)    ",
  tinyduck: "      ,>     ",
};
